config/routes.rb
Sprinter::Application.routes.draw do

  match 'alive' => 'application#alive'
  match 'sprints/reload_sprint_list' => 'sprints#reload_sprint_list'
  match 'sprints/:id/reload_sprint' => 'sprints#reload_sprint'

  resources :sprints do
    resources :cards
  end
  
  root :to => 'sprints#index'
  
  

end

app/models/sprint.rb
class Sprint < ActiveRecord::Base
  include ApplicationHelper
  has_many :cards
  attr_accessible :end_date, :name, :start_date, :xid

  def business_days_between(date1, date2)
    business_days = 0
    date = date2
    while date >= date1
     business_days = business_days + 1 unless date.saturday? or date.sunday?
     date = date - 1.day
    end
    business_days
  end
  
  def velocity
    self.cards.sum('points')
  end
  
  def type_count(type)
    self.cards.where("card_type = '#{type}'").count
  end
  
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  before_filter :get_sprints
  
  before_filter :validate_sprint, :only => :show
  
  def get_sprints
    @sprints = Sprint.all(:order => "name")
  end
  
  # GET /sprints
  # GET /sprints.json
  def index
    reload_sprint_list
    sprint = Sprint.find(:first, :order => "updated_at DESC")
    #sprint = Card.find(:first, :order => "card_updated DESC").sprint
    redirect_to sprint_path(sprint)
    
    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @sprints }
    # end
  end
  
  # def streamer
  #   self.response_body = Enumerator.new do |y|
  #     100000.times do |i|
  #       y << "This is line #{i}\n"
  #       self.response.headers['Last-Modified'] = Time.now.to_s
  #     end
  #   end
  # end
  
  def validate_sprint
    sprint = Sprint.find(params[:id])
    if sprint.start_date.nil? || sprint.end_date.nil? || sprint.start_date == sprint.end_date
      flash[:alert] = 'Sprint requires valid start and end dates'
      redirect_to edit_sprint_path(sprint)
    end
  end
  
  # GET /sprints/1
  # GET /sprints/1.json
  def show
    reload_sprint(params[:id])
        
    @sprint = Sprint.find(params[:id])
    
    @cards = @sprint.cards.order("card_updated desc")
    
    @card_days = @cards.group_by { |t| t.card_updated.beginning_of_day }
    
    @features = @cards.where("card_type = 'Story'")
    @bugs = @cards.where("card_type = 'Bug'")
    @tasks = @cards.where("card_type = 'Task'")
    
    @to_do = @cards.where("status IN ('Open','Reopened')").order("card_updated desc")
    @in_progress = @cards.where("status = 'In Progress'").order("card_updated desc")
    @in_review = @cards.where("status = 'In Review'").order("card_updated desc")
    @in_qa = @cards.where("status = 'In QA'").order("card_updated desc")
    @done = @cards.where("status = 'Closed'").order("card_updated desc")

    @wip = @cards.where("status IN ('In Progress','In Review', 'In QA')").order("card_updated desc")

    @done_each_day = []
    @points_remaining = []
    @days = []
    @target_points = []
    @target_high_points = []
    @target_low_points = [] 
    @days_in_sprint = (@sprint.end_date.to_date - @sprint.start_date.to_date).to_i+1
    @workdays_in_sprint = 0
    @points_this_sprint = @sprint.cards.sum('points')
    @workdays_in_sprint = work_days_between(@sprint.start_date,@sprint.end_date)
    @developers = @cards.where("status <> 'Open' AND (status <> 'Closed' OR (card_updated > '#{1.day.ago}'))").order("assignee, card_updated desc").group_by { |t| t.assignee }

    @sprint_progress_to_do = @to_do.sum('points').to_f / @points_this_sprint * 100
    @sprint_progress_wip = @wip.sum('points').to_f / @points_this_sprint * 100
    @sprint_progress_done = @done.sum('points').to_f / @points_this_sprint * 100

    days_so_far = 0
    done_so_far = 0
    index = 0
    
    @sprint.start_date.upto(@sprint.end_date) do |day|
      if day.strftime('%A') != 'Saturday' && day.strftime('%A') != 'Sunday'
        index = index + 1   
        target_point = @points_this_sprint - @points_this_sprint/@workdays_in_sprint.to_f*index
        target_high_point = target_point + target_point * 0.2
        target_low_point = target_point - target_point * 0.2
        @target_points << target_point
        @target_high_points << target_high_point
        @target_low_points << target_low_point
        @days << day.strftime('%a').to_s

        if day.to_date <= Time.now.in_time_zone.to_date
          days_so_far = days_so_far + 1
          done_this_day = 0
          @sprint.cards.each do |card|
            if card.status.to_s == 'Closed' && card.card_updated.to_date == day.to_date
              done_this_day = done_this_day + card.points.to_i
            end
          end
          done_so_far = done_so_far + done_this_day
          @points_remaining << @points_this_sprint - done_so_far      
        end 
      end
    end


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sprint }
    end
  end

  # GET /sprints/new
  # GET /sprints/new.json
  def new
    @sprint = Sprint.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sprint }
    end
  end

  # GET /sprints/1/edit
  def edit
    @sprint = Sprint.find(params[:id])
  end

  # POST /sprints
  # POST /sprints.json
  def create
    @sprint = Sprint.new(params[:sprint])

    respond_to do |format|
      if @sprint.save
        format.html { redirect_to @sprint, notice: 'Sprint was successfully created.' }
        format.json { render json: @sprint, status: :created, location: @sprint }
      else
        format.html { render action: "new" }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sprints/1
  # PUT /sprints/1.json
  def update
    @sprint = Sprint.find(params[:id])

    respond_to do |format|
      if @sprint.update_attributes(params[:sprint])
        format.html { redirect_to @sprint, notice: 'Sprint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sprints/1
  # DELETE /sprints/1.json
  def destroy
    @sprint = Sprint.find(params[:id])
    @sprint.destroy

    respond_to do |format|
      format.html { redirect_to sprints_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/views/sprints/_breakdown.html.erb
<div id="breakdown"></div>

<script>
var chart;
$(document).ready(function() {
	chart = new Highcharts.Chart({
		chart: {
			renderTo: 'breakdown'
		},
		title: {
			text: 'Breakdown'
		},
		subtitle: {
			text: '(issues)'
		},
		tooltip: {
			formatter: function() {
				return '<b>'+ this.point.name +'</b>: '+ this.y;
			}
		},
		plotOptions: {
			pie: {
				cursor: 'pointer',
				dataLabels: {
					enabled: true,
					formatter: function() {
					  valueDecimals: 0
						return '<b>'+ this.point.name +'</b>: '+ this.y;
					}
				}
			}
		},
		series: [{
			type: 'pie',
			data: [
			  ['Tasks',     <%= @tasks.count %>],		
				['Bugs',      <%= @bugs.count %>],
				['Features',  <%= @features.count %>]
			]
		}]
	});
});
</script>

app/views/sprints/_bucket.html.erb
  <% if bucket && bucket.count %>
    <% bucket.each do |card| %>
      <%= render 'card_label', :card => card %>
    <% end %>
  <% else %>
    No Issues
  <% end %>

app/views/sprints/_burndown.html.erb
<div id="burndown"></div>
<script>
  $(function(){
    var chart;
    chart = new Highcharts.Chart({
      chart: {
      			renderTo: 'burndown',
      			type: 'line',
            height:300
      		},
          credits: {
            enabled: false
          },
      		title: {
      			text: '<%= @sprint['name']%>',
            floating: true,
            align: 'right',
            y: 30
      		},
          legend: {
            enabled: false
          },
      		tooltip: {
            formatter: function() {
          	  return '<b>'+ this.series.name +'</b><br/>'+
          		this.x +': '+ this.y;
          	}
          },
      		xAxis: {
      			categories: <%= raw @days %>,
      			labels: {
              // rotation: -45,
      				align: 'center',
      				style: {
      					font: 'normal 13px Verdana, sans-serif'
      				}
            }
      		},
      		yAxis: {
      		  min: 0, 
      			title: {
      				text: ''
      			},
      			plotLines: [{
      				value: 0,
      				width: 1,
      				color: '#808080'
      			}]
      		},
      		series: [{
          	  name: 'Actual',
          	  marker: { symbol: 'circle' },
          	  dataLabels: { enabled: true },
          	  data: <%= @points_remaining %>
          	},{
          	  name: 'Target',
          	  marker: { enabled: false },
          	  color: '#559955',
          	  data: <%= @target_points %>
          	},{
          	  name: 'High',
          	  marker: { enabled: false },
          	  color: '#559955',
          	  dashStyle: 'Dash',
          	  data: <%= @target_high_points %>
          	},{
          	  name: 'Low',
          	  marker: { enabled: false },
          	  color: '#559955',
          	  dashStyle: 'Dash',
          	  data: <%= @target_low_points %>
          	}]
    });
  });
</script>

app/views/sprints/_card_label.html.erb
<% if card.card_type == 'Bug' %>
  <% badgeclass = 'label-important' %>
<% elsif card.card_type == 'Story' %>
  <% badgeclass = 'label-success' %>
<% elsif card.card_type == 'Task'  %>
  <% badgeclass = 'label-info' %>
<% else %>
  <% badgeclass = '' %>
<% end %>



<a class="card_label label <%= badgeclass %>"
	href="#"
  id="example1"
  rel="popover"
  data-trigger="hover"
  data-content="<h4><%= raw(card.summary).html_safe.gsub("\n", '<br/>') %></h4> <br> <%= truncate(raw(card.description).html_safe.gsub("\n", '<br/>'), :length => 180) %> "
  data-original-title="<a href='http://jira.wantsa.com:38881/browse/<%= card.key %>' target='_blank'><%= card.key %></a><% if card.card_type == 'Story' %> <span class='pull-right label <%= badgeclass %>'><%= pluralize(card.points,'point') %></span><% end %> "><%= card.key %></a>

app/views/sprints/_card_list.html.erb
<table class="table table-condensed table-hover">
  <% @card_days.sort.reverse.each do |day, cards| %>
    <thead>
      <tr>
        <td colspan="3"><h3><%= day.strftime('%A, %B %e, %Y') %></h3></td>
      </tr>
    </thead>
    <tbody>
    <% for card in cards %>
      <tr>
        <td style="white-space:nowrap"><%= render 'card_label', :card => card %></td>
        <td><strong><%= card.summary %></strong></td>
        <td style="white-space:nowrap"><strong><%= card.assignee %><br><%= card.card_status %></strong></td>
      </tr>
    <% end %>
    </tbody>
  <% end %>
</table>

app/views/sprints/_form.html.erb
<%= simple_form_for @sprint, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :xid %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sprints_path, :class => 'btn' %>
  </div>
<% end %>

app/views/sprints/_kanban_sprint.html.erb
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>To Do</th>
      <th>In Progress</th>
      <th>In Review</th>
      <th>In QA</th>
      <th>Done</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="width:20%"><% @to_do.each do |card| %><%= render 'card_label', :card => card %><% end %></td>
      <td style="width:20%"><% @in_progress.each do |card| %><%= render 'card_label', :card => card  %><% end %></td>
      <td style="width:20%"><% @in_review.each do |card| %><%= render 'card_label', :card => card  %><% end %></td>
      <td style="width:20%"><% @in_qa.each do |card| %><%= render 'card_label', :card => card  %><% end %></td>
      <td style="width:20%"><% @done.each do |card| %><%= render 'card_label', :card => card  %><% end %></td>
    </tr>

    <tr>
      <td><h6><%= pluralize(@to_do.sum('points'), 'Point') %></h6></td>
      <td><h6><%= pluralize(@in_progress.sum('points'), 'Point') %></h6></td>
      <td><h6><%= pluralize(@in_review.sum('points'), 'Point') %></h6></td>
      <td><h6><%= pluralize(@in_qa.sum('points'), 'Point') %></h6></td>
      <td><h6><%= pluralize(@done.sum('points'), 'Point') %></h6></td>
    </tr>
</table>

app/views/sprints/_kanban_team.html.erb
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>Team Member</th>
      <th>In Progress</th>
      <th>In Review</th>
      <th>In QA</th>
      <th>Done</th>
    </tr>
  </thead>
  <tbody>
    <% @developers.each do |developer,cards| %>
      <tr>
        <td style="width:20%"><%= developer %></td>
        <td style="width:20%"><% cards.each do |card| %><%= render 'card_label', :card => card if card.status == 'In Progress' %><% end %></td>
        <td style="width:20%"><% cards.each do |card| %><%= render 'card_label', :card => card if card.status == 'In Review' %><% end %></td>
        <td style="width:20%"><% cards.each do |card| %><%= render 'card_label', :card => card if card.status == 'In QA' %><% end %></td>
        <td style="width:20%"><% cards.each do |card| %><%= render 'card_label', :card => card if card.status == 'Closed' %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sprints/_progress.html.erb
<div id="progress"></div>

<script>
var chart;
$(document).ready(function() {
	chart = new Highcharts.Chart({
		chart: {
			renderTo: 'progress',
			type: 'column'
		},
		title: {
			text: 'Progress'
		},
		legend: {
      enabled: true
    },
    xAxis: {
      categories: ['Backlog','WIP',	'In Review', 'In QA','Done']
    },
    yAxis: {
      title: {
        text: ''
      }
    },			
		series: [{
		  name: 'Points',
			data: [
		    ['To Do', <%= @to_do.sum('points') %>],		
			  ['In Progress', <%= @in_progress.sum('points') %>],
			  ['In Review', <%= @in_review.sum('points') %>],
				['In QA', <%= @in_qa.sum('points') %>],      
				['Done', <%= @done.sum('points') %>]
			]
		},
		{
		  name: 'Issues',
			data: [
		    ['To Do', <%= @to_do.count %>],		
			  ['In Progress', <%= @in_progress.count %>],
			  ['In Review', <%= @in_review.count %>],
				['In QA', <%= @in_qa.count %>],      
				['Done', <%= @done.count %>]
			]
		}]
		
	});
});
</script>

app/views/sprints/edit.html.erb
<%- model_class = @sprint.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

    <div class="progress">
  <div class="bar bar-success" style="width: 35%;"></div>
  <div class="bar bar-warning" style="width: 20%;"></div>
  <div class="bar bar-danger" style="width: 10%;"></div>
</div>

app/views/sprints/index.html.erb
<div class="btn-group pull-right">
  <%= link_to raw("<i class='icon-plus'></i> New"), new_sprint_path, :class => 'btn' %>
</div>

<%- model_class = Sprint.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:end_date) %></th>
      <th>Work Days</th>
      <th>Velocity</th>
      <th>Features</th>
      <th>Bugs</th>
      <th>Tasks</th>
      <th>Issues</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @sprints.each do |sprint| %>
      <tr>
        <td><%= sprint.name %></td>
        <td><%= sprint.start_date %></td>
        <td><%= sprint.end_date %></td>
        <td><%= sprint.business_days_between(sprint.start_date, sprint.end_date) if sprint.start_date && sprint.end_date %></td>
        <td><%= sprint.velocity %></td>
        <td><%= sprint.type_count('Story') %></td>
        <td><%= sprint.type_count('Bug') %></td>
        <td><%= sprint.type_count('Task') %></td>
        <td><%= sprint.cards.count %></td>
        <td>
          <div class="btn-group pull-right">
            <% if sprint.start_date && sprint.start_date %>
            <%= link_to 'View', sprint_path(sprint), :class => 'btn btn-mini btn-success' %>
            <% end %>
            <%= link_to 'Edit', edit_sprint_path(sprint), :class => 'btn btn-mini btn-info' %>
            <%= link_to 'Destroy', sprint_path(sprint), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sprints/new.html.erb
<%- model_class = @sprint.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sprints/show.html.erb
<div class="row-fluid">
  <div class="span7">

    <div class="progress">
      <div class="bar bar-danger" style="width: <%= @sprint_progress_to_do %>%"><%= @to_do.sum('points') %></div>
      <div class="bar bar-warning" style="width: <%= @sprint_progress_wip %>%"><%= @wip.sum('points') %></div>
      <div class="bar bar-success" style="width: <%= @sprint_progress_done %>%"><%= @done.sum('points') %></div>
    </div>

    <div class="tabbable"> <!-- Only required for left/right tabs -->
      <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">Team</a></li>
        <li><a href="#tab2" data-toggle="tab">Sprint</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tab1">
          <%= render 'kanban_team' %>
        </div>
        <div class="tab-pane" id="tab2">
          <%= render 'kanban_sprint' %>
        </div>
      </div>
    </div>


    <div class="row-fluid">
      <div class="span6">
        <div class="well well-small">
          <%= render 'breakdown' %>
        </div>
      </div>
      <div class="span6">
        <div class="well well-small">
          <%= render 'progress' %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="span5">    
    <%= render 'burndown' %>

    <%= render 'card_list' %>
  </div>
</div>