config/routes.rb
Sprinter::Application.routes.draw do

  match 'alive' => 'application#alive'
  match 'sprints/reload_sprint_list' => 'sprints#reload_sprint_list'
  match 'sprints/:id/reload_sprint' => 'sprints#reload_sprint'

  resources :sprints do
    resources :cards
  end
  
  root :to => 'sprints#index'
  
  

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :sprint
  attr_accessible :assignee, :description, :key, :points, :sprint_id, :status, :summary, :type
  
  def card_status
    
    if self.status == 'Open' || self.status == 'Reopened'
      'To Do'
    elsif self.status == 'In Progress'
      'In Progress'
    elsif self.status == 'In Review'
      'In Review'
    elsif self.status == 'In QA'
      'In QA'
    elsif self.status == 'Closed'
      'Done'
    end

  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper

  
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :assignee %><br />
    <%= f.text_field :assignee %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :sprint_id %><br />
    <%= f.number_field :sprint_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <tr>
    <th>Summary</th>
    <th>Description</th>
    <th>Assignee</th>
    <th>Points</th>
    <th>Status</th>
    <th>Key</th>
    <th>Sprint</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cards.each do |card| %>
  <tr>
    <td><%= card.summary %></td>
    <td><%= card.description %></td>
    <td><%= card.assignee %></td>
    <td><%= card.points %></td>
    <td><%= card.status %></td>
    <td><%= card.key %></td>
    <td><%= card.sprint_id %></td>
    <td><%= card.type %></td>
    <td><%= link_to 'Show', card %></td>
    <td><%= link_to 'Edit', edit_card_path(card) %></td>
    <td><%= link_to 'Destroy', card, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Summary:</b>
  <%= @card.summary %>
</p>

<p>
  <b>Description:</b>
  <%= @card.description %>
</p>

<p>
  <b>Assignee:</b>
  <%= @card.assignee %>
</p>

<p>
  <b>Points:</b>
  <%= @card.points %>
</p>

<p>
  <b>Status:</b>
  <%= @card.status %>
</p>

<p>
  <b>Key:</b>
  <%= @card.key %>
</p>

<p>
  <b>Sprint:</b>
  <%= @card.sprint_id %>
</p>

<p>
  <b>Type:</b>
  <%= @card.type %>
</p>


<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>