config/routes.rb
Sprinter::Application.routes.draw do

  match 'alive' => 'application#alive'
  match 'sprints/reload_sprint_list' => 'sprints#reload_sprint_list'
  match 'sprints/:id/reload_sprint' => 'sprints#reload_sprint'

  resources :sprints do
    resources :cards
  end
  
  root :to => 'sprints#index'
  
  

end

app/views/layouts/_about.html.erb
<div class="modal hide" id="aboutSprinter">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Sprinter</h3>
  </div>
  <div class="modal-body">
    <p>Version: <%= APP_VERSION %></p>
    <p>Sprinter is designed to be a useful sprint monitoring tool.</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sprinter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        
        <a class="brand" href="/sprints"> Sprinter</a>
        
        <div class="nav-collapse ">
          <ul class="nav pull-right">
            <li><a href="">Last Updated: <%= Time.now.in_time_zone.strftime('%B %e %Y %l:%M %p') %></a></li>
            <% if @sprint %>
              <li><a href=""><span id="nav_update" class="badge badge-success"><i class="icon-time"></i> <span id="countdown"></span></span></a></li>
            <% end %>
          </ul>
        </div>
        
        <div class="nav-collapse">
          <ul class="nav">            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sprints <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/sprints">Update Sprints</a></li>
                <li class="divider"></li>
                <% @sprints.each do |sprint| %>
                <li><a href="<%= sprint_path(sprint) %>"><%= sprint.name %></a></li>
                <% end %>
              </ul>
            </li>
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-cog"></i> Settings <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="<%= edit_sprint_path(@sprint) %>">Edit Sprint</a></li>
                <li><a data-toggle="modal" href="#aboutSprinter">About Sprinter</a></li>
              </ul>
            </li>
          </ul>
        </div>
        
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <% flash.each do |name, msg| %>
      <div class="alert fade in alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&times;</a>
        <%= msg  %>
      </div>
    <% end %>
      <%= yield %>
  </div>

  <%= render 'layouts/about' %>


</body>
</html>